name: Tests
on:
  push:
    branches: ['**']
    paths-ignore: ['**.md', '**.sh', '.github/workflows/*.yml']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', '**.sh', '.github/workflows/*.yml']
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  test:
    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore -v minimal --nologo

      - name: Build
        run: dotnet build -c Release -p:TreatWarningsAsErrors=true -v minimal --no-restore --nologo -clp:NoSummary

      - name: Run tests
        run: dotnet test -c Release -v minimal --no-build --nologo
